# Workflow to automatically lint gdscript code
name: gdlint on push

on:
  [push, pull_request]

jobs:
  gdlint:
    name: gdlint scripts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install 'gdtoolkit==4.*'
      - name: Lint Godot XR Tools
        run: |
          gdlint addons/godot-xr-tools

